"""Machine states for the application FSM."""

from __future__ import annotations

from enum import StrEnum


class MachineState(StrEnum):
    BOOT = "BOOT"
    SELF_TEST = "SELF_TEST"
    IDLE = "IDLE"
    PRODUCT_SELECTED = "PRODUCT_SELECTED"
    CHECKING_AVAILABILITY = "CHECKING_AVAILABILITY"
    CHECKING_CHANGE = "CHECKING_CHANGE"
    WAITING_FOR_PAYMENT = "WAITING_FOR_PAYMENT"
    ACCEPTING_CASH = "ACCEPTING_CASH"
    PAYMENT_ACCEPTED = "PAYMENT_ACCEPTED"
    DISPENSING_CHANGE = "DISPENSING_CHANGE"
    DISPENSING_PRODUCT = "DISPENSING_PRODUCT"
    OPENING_DELIVERY_WINDOW = "OPENING_DELIVERY_WINDOW"
    WAITING_FOR_CUSTOMER_PICKUP = "WAITING_FOR_CUSTOMER_PICKUP"
    CLOSING_DELIVERY_WINDOW = "CLOSING_DELIVERY_WINDOW"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    OUT_OF_SERVICE = "OUT_OF_SERVICE"
    FAULT = "FAULT"
    SERVICE_MODE = "SERVICE_MODE"
    RECOVERY_PENDING = "RECOVERY_PENDING"
